:/ script Pipeline //
node {
       stage(' Env Check') {
        if (`sh config/docker-check` == true)
         sh " echo "Docker Exist" "
        else 
         sh "ansible-playbook -C config/playbooks/site.yaml -i config/playbooks/hosts -t docker"                
         } 

       stage('TST Deploy') {
         sh "ansible-playbook -C config/playbooks/site.yaml -i config/playbooks/hosts -t tstenv"
               }
        stage('PRD Deploy') {
         sh "ansible-playbook -C config/playbooks/site.yaml -i config/playbooks/hosts -t prdenv"
            }
}
